<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot_boat">

    <xacro:include filename="$(find robot_boat_description_pkg)/urdf/robot_boat.gazebo.xacro" />

    <xacro:gazebo_elements />




<!-- Properties -->
<xacro:property name="body_width" value="1.0"/>
<xacro:property name="body_lenght" value="2.0"/>
<xacro:property name="body_height" value="1.0"/>

<xacro:property name="wheel_width" value="0.2"/>
<xacro:property name="wheel_radius" value="0.1"/>
<xacro:property name="wheel_distance" value="body_width"/>

<xacro:property name="caster_radius" value="0.1"/>

        
  <material name="red">
      <color rgba="1.0 0.0 0.0 1"/>
  </material>

  <material name="green_light">
      <color rgba="0.0 1.0 0.0 1"/>
  </material>

  <material name="green_dark">
    <color rgba="0.0 0.5 0.0 1"/>
  </material>

  <material name="blue">
      <color rgba="0.0 0.0 1.0 1"/>
  </material>

  <link name="base_link">
  </link>


  <!-- Body -->
  <link name="chassis">
    <visual>
      <geometry>
        <mesh filename="package://robot_boat_description_pkg/meshes/cute_cube.dae" scale="${body_lenght} ${body_width}  ${body_height}"/>
      </geometry>
    </visual>

    <collision>
      <geometry>
        <box size="${body_lenght} ${body_width} ${body_height}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.1"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.0008333333333333335" ixy="0" ixz="0" iyy="0.0008333333333333335" iyz="0" izz="0.0008333333333333335"/>
    </inertial>

  </link>

  <joint name="base_link_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 ${body_height / 2.0}" />
    <parent link="base_link" />
    <child link="chassis" />
  </joint>

    <!-- Wheel Macro -->
    <xacro:macro name="wheel" params="wheel_name">
    <link name="${wheel_name}">    
        <visual>
            <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
            <geometry>
            <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
        </visual>

        <collision>
            <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
            <geometry>
            <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
        </collision>

        <inertial>
            <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
            <mass value="0.1"/>
            <inertia ixx="1.531666666666667e-05" ixy="0" ixz="0" iyy="1.531666666666667e-05" iyz="0" izz="3.0625000000000006e-05"/>
        </inertial>
    </link>
    </xacro:macro>


    <!-- Wheel Left -->
    <xacro:wheel wheel_name="left_wheel" />

    <!-- Wheel Right -->
    <xacro:wheel wheel_name="right_wheel" />





  <joint name="joint_left_wheel" type="continuous">
    <origin rpy="0 0 0" xyz="0 ${body_width/2} -${body_height/2}"/>
    <child link="left_wheel"/>
    <parent link="chassis"/>
    <axis rpy="0 0 0" xyz="0 1 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="10.0" friction="10.0"/>
  </joint>


  <joint name="joint_right_wheel" type="continuous">  
    <origin rpy="0 0 0" xyz="0 -${body_width/2} -${body_height/2}"/>
    <child link="right_wheel"/>
    <parent link="chassis"/>
    <axis rpy="0 0 0" xyz="0 1 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="10.0" friction="10.0"/>
  </joint>


  <!-- Caster Wheel Front -->
  <link name="front_yaw_link">
      <visual>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <geometry>          
          <cylinder length="0.001" radius="0.0045000000000000005"/>
        </geometry>
        <material name="blue"/>
      </visual>

      <collision>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <geometry>
          <cylinder length="0.001" radius="0.0045000000000000005"/>
        </geometry>
      </collision>

      <inertial>
          <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
          <mass value="0.001"/>
          <inertia ixx="5.145833333333334e-09" ixy="0" ixz="0" iyy="5.145833333333334e-09" iyz="0" izz="1.0125000000000003e-08"/>
      </inertial>

  </link>

  <joint name="front_yaw_joint" type="continuous">
    <origin rpy="0 0 0" xyz="${body_lenght / 2 - 0.1} 0 -${body_height / 2 - 0.05 }" />
    <parent link="chassis" />
    <child link="front_yaw_link" />
    <axis xyz="0 0 1" />
    <limit effort="1000.0" velocity="100.0" />
    <dynamics damping="0.0" friction="0.1"/>
  </joint>




  <link name="front_roll_link">
      <visual>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <geometry>
          <cylinder length="0.001" radius="0.0045000000000000005"/>
        </geometry>
        <material name="red"/>
      </visual>

      <collision>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <geometry>
          <cylinder length="0.001" radius="0.0045000000000000005"/>
        </geometry>
      </collision>

      <inertial>
          <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
          <mass value="0.001"/>
          <inertia ixx="5.145833333333334e-09" ixy="0" ixz="0" iyy="5.145833333333334e-09" iyz="0" izz="1.0125000000000003e-08"/>
      </inertial>
  </link>

  <joint name="front_roll_joint" type="continuous">
    <origin rpy="0 0 0" xyz="0 0 0" />
    <parent link="front_yaw_link" />
    <child link="front_roll_link" />
    <axis xyz="1 0 0" />
    <limit effort="1000.0" velocity="100.0" />
    <dynamics damping="0.0" friction="0.1"/>
  </joint>



  <link name="front_pitch_link">
    <visual>
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="green_dark"/>
    </visual>

    <collision>
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
    </collision>

    <inertial>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <mass value="0.001"/>
        <inertia ixx="4e-08" ixy="0" ixz="0" iyy="4e-08" iyz="0" izz="4e-08"/>
    </inertial>
  </link>

  <joint name="front_pitch_joint" type="continuous">
    <origin rpy="0 0 0" xyz="0 0 0" />
    <parent link="front_roll_link" />
    <child link="front_pitch_link" />
    <axis xyz="0 1 0" />
    <limit effort="1000.0" velocity="100.0" />
    <dynamics damping="0.0" friction="0.1"/>
  </joint>

<!-- Caster Wheel Back -->
  <link name="back_yaw_link">
    <visual>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <geometry>
          <cylinder length="0.001" radius="0.0045000000000000005"/>
        </geometry>
        <material name="blue"/>
      </visual>

      <collision>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <geometry>
          <cylinder length="0.001" radius="0.0045000000000000005"/>
        </geometry>
      </collision>

      <inertial>
          <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
          <mass value="0.001"/>
          <inertia ixx="5.145833333333334e-09" ixy="0" ixz="0" iyy="5.145833333333334e-09" iyz="0" izz="1.0125000000000003e-08"/>
      </inertial>
  </link>

  <joint name="back_yaw_joint" type="continuous">
    <origin rpy="0 0 0" xyz="-${body_lenght / 2.0 - 0.1} 0 -${body_height / 2 - 0.05 }" />
    <parent link="chassis" />
    <child link="back_yaw_link" />
    <axis xyz="0 0 1" />
    <limit effort="1000.0" velocity="100.0" />
    <dynamics damping="0.0" friction="0.1"/>
  </joint>





  <link name="back_roll_link">
      <visual>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <geometry>
          <cylinder length="0.001" radius="0.0045000000000000005"/>
        </geometry>
        <material name="red"/>
      </visual>

      <collision>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <geometry>
          <cylinder length="0.001" radius="0.0045000000000000005"/>
        </geometry>
      </collision>

      <inertial>
          <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
          <mass value="0.001"/>
          <inertia ixx="5.145833333333334e-09" ixy="0" ixz="0" iyy="5.145833333333334e-09" iyz="0" izz="1.0125000000000003e-08"/>
      </inertial>
  </link>

  <joint name="back_roll_joint" type="continuous">
    <origin rpy="0 0 0" xyz="0 0 0" />
    <parent link="back_yaw_link" />
    <child link="back_roll_link" />
    <axis xyz="1 0 0" />
    <limit effort="1000.0" velocity="100.0" />
    <dynamics damping="0.0" friction="0.1"/>
  </joint>



  <link name="back_pitch_link">
    <visual>
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="green_light"/>
    </visual>

    <collision>
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
    </collision>

    <inertial>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <mass value="0.001"/>
        <inertia ixx="4e-08" ixy="0" ixz="0" iyy="4e-08" iyz="0" izz="4e-08"/>
    </inertial>
  </link>


  <joint name="back_pitch_joint" type="continuous">
    <origin rpy="0 0 0" xyz="0 0 0" />
    <parent link="back_roll_link" />
    <child link="back_pitch_link" />
    <axis xyz="0 1 0" />
    <limit effort="1000.0" velocity="100.0" />
    <dynamics damping="0.0" friction="0.1"/>
  </joint>

  <!-- PLUGINS -->

  <!-- JOINT PUBLISHER -->
  <gazebo>
    <plugin name="box_bot_joint_state" filename="libgazebo_ros_joint_state_publisher.so">
      <ros>
          <remapping>~/out:=joint_states</remapping>
      </ros>
      <update_rate>30</update_rate>

      <joint_name>joint_left_wheel</joint_name>
      <joint_name>joint_right_wheel</joint_name>
      <joint_name>front_yaw_joint</joint_name>
      <joint_name>back_yaw_joint</joint_name>
      <joint_name>front_roll_joint</joint_name>
      <joint_name>back_roll_joint</joint_name>
      <joint_name>front_pitch_joint</joint_name>
      <joint_name>back_pitch_joint</joint_name>
      
    </plugin>
  </gazebo>

  <!-- Differential drive -->
  <gazebo>
    <plugin filename="libgazebo_ros_diff_drive.so" name="differential_drive_controller">

        <ros>
            <namespace>robot_boat</namespace>
            <remapping>/odom:=odom</remapping>
        </ros>
    
        <update_rate>50</update_rate>
        <!-- Wheel joints -->
        <left_joint>joint_left_wheel</left_joint>
        <right_joint>joint_right_wheel</right_joint>
        <!-- Kinematics -->
        <wheel_separation>0.1</wheel_separation>
        <wheel_diameter>0.07</wheel_diameter>
        <publish_odom>true</publish_odom>
        <!-- TF frames -->
        <publish_odom_tf>true</publish_odom_tf>
        <publish_wheel_tf>false</publish_wheel_tf>
        <odometry_frame>odom</odometry_frame>
        <robot_base_frame>base_link</robot_base_frame>
        <!-- Limits -->
        <max_wheel_torque>1.0</max_wheel_torque>
        <max_wheel_acceleration>2.0</max_wheel_acceleration>

    </plugin>
  </gazebo>


    <!-- Laser Position Control-->

  <link name="laser_scan_link">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://robot_boat_description_pkg/meshes/sensors/rplidar.dae" scale="1.0 1.0 1.0"/>
      </geometry>
    </visual>

    <collision>
       <origin rpy="0 0 0" xyz="0 0 0.0204"/>
      <geometry>
        <cylinder length="0.0408" radius="0.037493"/>
      </geometry>
    </collision>

    <inertial>

      <mass value="0.01"/>
      <origin rpy="0 0 0" xyz="0 0 0.0204"/>
      <inertia ixx="6.066578520833334e-06" ixy="0" ixz="0" iyy="6.072950163333333e-06" iyz="0" izz="9.365128684166666e-06"/>
    </inertial>
  </link>

  <joint name="laser_scan_link_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0.0 0.0 0.05"/>
    <parent link="chassis"/>
    <child link="laser_scan_link"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.1" upper="0.0" effort="20.0" velocity="2.0"/>
    <dynamics damping="0.1" friction="1.0"/>
  </joint>

  <link name="laser_scan_frame">
  </link>

  <joint name="laser_scan_frame_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0.03"/>
    <parent link="laser_scan_link"/>
    <child link="laser_scan_frame"/>
    <axis xyz="0 0 0"/>
  </joint>

  
  <!-- Lser plugin -->
<gazebo reference="laser_scan_frame">
    <sensor name="sensor_ray" type="ray">
        <pose>0 0 0 0 0 0</pose>
        <ray>
          <scan>
            <horizontal>
              <samples>720</samples>
              <resolution>1.0</resolution>
              <min_angle>-3.14</min_angle>
              <max_angle>3.14</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.2</min>
            <max>20</max>
          </range>
        </ray>
        <always_on>true</always_on>
        <visualize>false</visualize>
        <update_rate>10.0</update_rate>
        <plugin name="laser" filename="libgazebo_ros_ray_sensor.so">
          <ros>
            <namespace>/robot_boat</namespace>
            <remapping>~/out:=laser_scan</remapping>
          </ros>
          <output_type>sensor_msgs/LaserScan</output_type>
        </plugin>
    </sensor>
</gazebo>


</robot>